name: Publish Firebase App

on:
  push:
    branches:
      - devfest_2019

jobs:
  publish:
    name : Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Install dependencies
        run: npm ci
      - name: Build Application
        run: npm run dist
      - name: Deploy Firebase Host
        uses: pizzafox/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: sfeir-pokedex
        with:
          args: deploy
